# PHPUnit Workflow

name: PHPUnit

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: corepack enable && yarn install --immutable

      - name: Build scripts
        run: yarn prod

      #- name: Install WP Tests
        #run: bash bin/install-wp-tests.sh wordpress_test root root localhost latest

      #- name: phpunit tests
        #run: ./vendor/bin/phpunit

      #- name: PHPUnit tests
        #uses: php-actions/phpunit@v3
        #with:
          #configuration: phpunit.xml.dist
